Repository GSG-FC03/Cookit, pull requests merged in 2021-08, with the labels that each got.

#15 Create structure
  LandingPage/script.js
  LandingPage/style.css
  Main/main.css
  Main/main.html
  Main/main.js
  assets/chef.png
  index.html
  recipe/recipe.css
  recipe/recipe.html
  recipe/recipe.js
Labels: done

#16 landing page html file >Relates#13
  index.html
Labels: done

#17 landing page CSS file >Relates #14
  LandingPage/style.css
Labels: done

#26 #25 home page reconstructing
  Main/main.css
  Main/main.html
  Main/main.js
Labels: URGENT

#28 main page JS file change value
  Main/main.css
  Main/main.js
Labels: done, Awaiting-Review

#29 CousinePage
  cousins/cousins.js
  cousins/cuisine.css
  cousins/cuisine.html
Labels: Awaiting-Review

#32 search function in the cuisine page
  cousins/cousins.js
  cousins/cuisine.html
Labels: done

#20 Landing page responsive design #19
  LandingPage/style.css
  index.html
Labels: done, Awaiting-Review

#38 36 addbackbutton
  cousins/cousins.js
  cousins/cuisine.css
  cousins/cuisine.html
Labels: done

#22 Recipe page
  cousins/cousins.js
  recipe/recipe.css
  recipe/recipe.html
  recipe/recipe.js
Labels: Awaiting-Review

#41 modify cuisine page css file >relates #33
  cousins/cuisine.css
Labels: Awaiting-Review
